# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MENU(object):
    def setupUi(self, MENU):
        MENU.setObjectName("MENU")
        MENU.resize(823, 600)
        self.centralwidget = QtWidgets.QWidget(MENU)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_bg = QtWidgets.QListView(self.centralwidget)
        self.menu_bg.setGeometry(QtCore.QRect(0, 0, 821, 571))
        self.menu_bg.setStyleSheet("background-image: url(:/bg2.jpg);\n"
"")
        self.menu_bg.setObjectName("menu_bg")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(320, 130, 140, 50))
        self.Button1.setStyleSheet("font: 75 14pt \"Arial\";\n"
"background-color: rgb(255, 255, 127);\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.Button1.setObjectName("Button1")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(320, 210, 140, 50))
        self.Button2.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: rgb(255, 255, 127);")
        self.Button2.setObjectName("Button2")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(320, 290, 140, 50))
        self.Button3.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: rgb(255, 255, 127);")
        self.Button3.setObjectName("Button3")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button4.setGeometry(QtCore.QRect(320, 370, 140, 50))
        self.Button4.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: rgb(255, 255, 127);")
        self.Button4.setObjectName("Button4")
        self.menu_label = QtWidgets.QLabel(self.centralwidget)
        self.menu_label.setGeometry(QtCore.QRect(250, 30, 281, 71))
        self.menu_label.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 28pt \"Algerian\";\n"
"")
        self.menu_label.setObjectName("menu_label")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button5.setGeometry(QtCore.QRect(320, 450, 140, 50))
        self.Button5.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: rgb(255, 255, 127);")
        self.Button5.setObjectName("Button5")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(480, 310, 191, 30))
        self.lineEdit1.setPlaceholderText("输入图片名称")
        self.lineEdit1.setStyleSheet("font: 75 12pt \"Arial\";")
        self.lineEdit1.setText("")
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(480, 390, 191, 30))
        self.lineEdit2.setPlaceholderText("输入视频名称")
        self.lineEdit2.setStyleSheet("font: 75 12pt \"Arial\";")
        self.lineEdit2.setObjectName("lineEdit2")
        MENU.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MENU)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        MENU.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MENU)
        self.statusbar.setObjectName("statusbar")
        MENU.setStatusBar(self.statusbar)

        self.retranslateUi(MENU)
        QtCore.QMetaObject.connectSlotsByName(MENU)

    def retranslateUi(self, MENU):
        _translate = QtCore.QCoreApplication.translate
        MENU.setWindowTitle(_translate("MENU", "MainWindow"))
        self.Button1.setText(_translate("MENU", "批量图片识别"))
        self.Button2.setText(_translate("MENU", "查看图片"))
        self.Button3.setText(_translate("MENU", "单张图片识别"))
        self.Button4.setText(_translate("MENU", "视频识别"))
        self.menu_label.setText(_translate("MENU", "处理操作选择"))
        self.Button5.setText(_translate("MENU", "退出"))
import bg_picture_rc
