# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(784, 620)
        self.centralwidget = QtWidgets.QWidget(LOGIN)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QListView(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.bg.setStyleSheet("background-image: url(:/bg2.jpg);\n"
"\n"
"\n"
"")
        self.bg.setObjectName("bg")
        self.loginbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutton.setGeometry(QtCore.QRect(240, 370, 101, 31))
        self.loginbutton.setStyleSheet("\n"
"font: 75 14pt \"Arial\";\n"
"background-color: rgb(255, 255, 255);")
        self.loginbutton.setObjectName("loginbutton")
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(470, 370, 101, 31))
        self.exitbutton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Arial\";")
        self.exitbutton.setObjectName("exitbutton")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(240, 220, 91, 61))
        self.username.setStyleSheet("font: 16pt \"Agency FB\";\n"
"color: rgb(255, 255, 0);\n"
"")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(240, 300, 84, 32))
        self.password.setStyleSheet("font: 16pt \"Agency FB\";\n"
"color: rgb(255, 255, 0);\n"
"")
        self.password.setObjectName("password")
        self.username_line = QtWidgets.QLineEdit(self.centralwidget)
        self.username_line.setGeometry(QtCore.QRect(370, 240, 221, 31))
        self.username_line.setPlaceholderText("提示:kk")
        self.username_line.setObjectName("username_line")
        self.password_line = QtWidgets.QLineEdit(self.centralwidget)
        self.password_line.setGeometry(QtCore.QRect(370, 300, 221, 31))
        self.password_line.setPlaceholderText("提示:123456")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setObjectName("password_line")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(310, 130, 181, 81))
        self.welcome.setStyleSheet("font: 24pt \"Agency FB\";\n"
"color: rgb(255, 255, 0);")
        self.welcome.setObjectName("welcome")
        LOGIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LOGIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 26))
        self.menubar.setObjectName("menubar")
        LOGIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LOGIN)
        self.statusbar.setObjectName("statusbar")
        LOGIN.setStatusBar(self.statusbar)

        self.retranslateUi(LOGIN)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "MainWindow"))
        self.loginbutton.setText(_translate("LOGIN", "Login"))
        self.exitbutton.setText(_translate("LOGIN", "Exit"))
        self.username.setText(_translate("LOGIN", "Username"))
        self.password.setText(_translate("LOGIN", "Password"))
        self.welcome.setText(_translate("LOGIN", "欢迎登录"))
import bg_picture_rc
